apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-ai-matcher-config
data:
  DATABASE_URL: "jdbc:postgresql://<RDS_ENDPOINT>:<RDS_PORT>/<DB_NAME>"
  S3_BUCKET: "<S3_BUCKET_NAME>"
  OTHER_CONFIG_KEY: "value"