apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-temp-pvc
  namespace: jobvector
  labels:
    app: backend
    volume: temp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
