apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: jobvector
  labels:
    app: backend
type: Opaque
stringData:
  DB_PASSWORD: "pass123456"
  JWT_SECRET: "your-secret-key-change-this-in-production-minimum-256-bits"
  JWT_EXPIRATION: "86400000"
